---
abstract: 'Make CGI.pm stateless for use in persistent environment'
author:
  - 'Alex Efros  C<< <powerman-asdf@ya.ru> >>'
  - 'Alex Efros <powerman-asdf@ya.ru>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Stateless
no_index:
  directory:
    - inc
    - t
recommends:
  Pod::Coverage: 0.18
  Test::CheckManifest: 0.9
  Test::Perl::Critic: 0
  Test::Pod: 1.22
  Test::Pod::Coverage: 1.08
requires:
  perl: 5.8.8
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.000002
